//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string Broj {
            get {
                return ResourceManager.GetString("Broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Drzava {
            get {
                return ResourceManager.GetString("Drzava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose favourite team:.
        /// </summary>
        public static string FavTim {
            get {
                return ResourceManager.GetString("FavTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string Golovi {
            get {
                return ResourceManager.GetString("Golovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language:.
        /// </summary>
        public static string Jezik {
            get {
                return ResourceManager.GetString("Jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string Nerijeseno {
            get {
                return ResourceManager.GetString("Nerijeseno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose opponent:.
        /// </summary>
        public static string OppTim {
            get {
                return ResourceManager.GetString("OppTim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Pitanje {
            get {
                return ResourceManager.GetString("Pitanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string Pobjede {
            get {
                return ResourceManager.GetString("Pobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string Porazi {
            get {
                return ResourceManager.GetString("Porazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Postavke {
            get {
                return ResourceManager.GetString("Postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string Pozicija {
            get {
                return ResourceManager.GetString("Pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose championship:.
        /// </summary>
        public static string Prvenstvo {
            get {
                return ResourceManager.GetString("Prvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose screen size:.
        /// </summary>
        public static string Rezolucija {
            get {
                return ResourceManager.GetString("Rezolucija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find more....
        /// </summary>
        public static string Saznaj {
            get {
                return ResourceManager.GetString("Saznaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Spremi {
            get {
                return ResourceManager.GetString("Spremi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played matches:.
        /// </summary>
        public static string Utakmice {
            get {
                return ResourceManager.GetString("Utakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Zatvori {
            get {
                return ResourceManager.GetString("Zatvori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string Zuti {
            get {
                return ResourceManager.GetString("Zuti", resourceCulture);
            }
        }
    }
}
